# Generated by Django 2.2.3 on 2019-07-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('language', models.CharField(help_text='Entrer le langage majoritairement utilisé dans votre projet', max_length=10)),
                ('git', models.URLField(help_text='Entrer le lien de votre page Github ou Gitlab')),
                ('article', models.TextField()),
                ('mignature', models.ImageField(blank=True, null=True, upload_to='projets/%Y/%m/%d')),
                ('screenshot_1', models.ImageField(blank=True, null=True, upload_to='projets/%Y/%m/%d')),
                ('screenshot_2', models.ImageField(blank=True, null=True, upload_to='projets/%Y/%m/%d')),
                ('screenshot_3', models.ImageField(blank=True, null=True, upload_to='projets/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('font_size', models.IntegerField()),
            ],
        ),
    ]
