# Generated by Django 2.2.3 on 2019-07-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
