# Generated by Django 2.2.3 on 2019-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0002_document_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='da', upload_to='uploads/<django.db.models.fields.CharField>'),
            preserve_default=False,
        ),
    ]
