# Generated by Django 2.2.3 on 2019-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0003_auto_20190717_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
