# Generated by Django 2.2.3 on 2019-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0004_auto_20190717_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='docfile',
            field=models.FileField(default='test', upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
