# Generated by Django 2.2.3 on 2019-07-17 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0005_auto_20190717_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docfile',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='default', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.CharField(default='defaul', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
