# Generated by Django 2.2.3 on 2019-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0006_auto_20190717_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
