# Generated by Django 2.2.3 on 2019-07-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0007_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
