# Generated by Django 2.2.3 on 2019-07-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0008_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='git',
            field=models.URLField(blank=True, help_text='Entrer le lien de votre page Github ou Gitlab'),
        ),
    ]
