# Generated by Django 2.2.3 on 2019-07-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0009_auto_20190725_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='site',
            field=models.URLField(blank=True, help_text='Entrer le lien du site du projet'),
        ),
    ]
