# Generated by Django 2.2.3 on 2019-08-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0011_vekflix'),
    ]

    operations = [
        migrations.AddField(
            model_name='vekflix',
            name='url',
            field=models.CharField(default='best_of_tanguy', max_length=100),
            preserve_default=False,
        ),
    ]
