# Generated by Django 2.2.3 on 2019-08-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0012_vekflix_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vekflix',
            old_name='url',
            new_name='lien',
        ),
    ]
