# Generated by Django 2.2.3 on 2019-08-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0013_auto_20190808_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vekflix',
            name='jacket',
            field=models.ImageField(help_text='Format 150px/250px ', upload_to='vekflix/image/'),
        ),
        migrations.AlterField(
            model_name='vekflix',
            name='main_actor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vekflix',
            name='mignature',
            field=models.ImageField(help_text='Format 16/9', upload_to='vekflix/image/'),
        ),
        migrations.AlterField(
            model_name='vekflix',
            name='realisator',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
