# Generated by Django 2.2.4 on 2019-08-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0015_vekflix_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
