# Generated by Django 2.2.4 on 2019-08-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0016_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarreRaccourcie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
