# Generated by Django 2.2.4 on 2019-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0017_barreraccourcie'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
