# Generated by Django 2.2.4 on 2019-08-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0018_document_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='password',
            field=models.CharField(blank=True, help_text="Mot de passe facultatif demandé à l'ouverture du fichier", max_length=100, null=True),
        ),
    ]
