# Generated by Django 2.2.4 on 2019-08-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0019_auto_20190818_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='password_needed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
