# Generated by Django 2.2.4 on 2019-08-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0020_document_password_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='password_needed',
        ),
    ]
