# Generated by Django 2.2.4 on 2019-08-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0021_remove_document_password_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='order',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
