# Generated by Django 2.2.4 on 2019-08-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0022_projet_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='order',
            field=models.SlugField(blank=True, max_length=140, null=True),
        ),
    ]
