# Generated by Django 2.2.4 on 2019-08-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0023_auto_20190820_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='order',
        ),
        migrations.AddField(
            model_name='barreraccourcie',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
