# Generated by Django 2.2.4 on 2019-08-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0024_auto_20190824_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPasswords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
