# Generated by Django 2.2.4 on 2019-08-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0025_uploadpasswords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadPasswords',
            new_name='UploadPassword',
        ),
    ]
