# Generated by Django 2.2.4 on 2019-08-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0026_auto_20190825_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='mignature',
            field=models.ImageField(blank=True, null=True, upload_to='projets/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='screenshot_1',
            field=models.ImageField(blank=True, null=True, upload_to='projets/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='screenshot_2',
            field=models.ImageField(blank=True, null=True, upload_to='projets/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='screenshot_3',
            field=models.ImageField(blank=True, null=True, upload_to='projets/'),
        ),
    ]
