# Generated by Django 2.2.5 on 2019-09-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0027_auto_20190826_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='mignature',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='screenshot_1',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='screenshot_2',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='screenshot_3',
        ),
    ]
