# Generated by Django 2.2.5 on 2019-10-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0029_vekflix_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('resume', models.TextField()),
                ('avis', models.TextField()),
                ('note', models.CharField(help_text='Note sur 5', max_length=1)),
                ('couverture', models.ImageField(upload_to='blog_coline/image/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
