# Generated by Django 2.2.5 on 2019-10-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0030_livre'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
