# Generated by Django 2.2.5 on 2019-10-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0031_livre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='auteur',
            field=models.CharField(default='george orwell', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livre',
            name='genre',
            field=models.CharField(default='geor', max_length=100),
            preserve_default=False,
        ),
    ]
