# Generated by Django 2.2.5 on 2019-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0032_auto_20191029_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('realisateur', models.CharField(max_length=100)),
                ('synopsis', models.TextField()),
                ('avis', models.TextField()),
                ('note', models.CharField(help_text='Note sur 5', max_length=1)),
                ('jaquette', models.ImageField(upload_to='blog_coline/image/')),
                ('acteurs', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
