# Generated by Django 2.2.5 on 2019-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0033_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='acteurs',
            field=models.TextField(help_text='Un acteur par ligne'),
        ),
    ]
