# Generated by Django 2.2.5 on 2020-01-31 13:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0038_facerecognition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Livre',
        ),
        migrations.AddField(
            model_name='facerecognition',
            name='color',
            field=colorfield.fields.ColorField(default='#00FF00', max_length=18),
        ),
    ]
