# Generated by Django 2.2.5 on 2020-01-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0039_auto_20200131_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facerecognition',
            name='color',
        ),
    ]
