# Generated by Django 2.2.5 on 2020-02-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0040_remove_facerecognition_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lang', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
            ],
        ),
    ]
