# Generated by Django 2.2.5 on 2020-02-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0043_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='annee',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
