# Generated by Django 2.2.5 on 2020-02-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_hub', '0044_exercice_annee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
